version: "3.8"

services:

  backend:
    build:
        context: ./
        dockerfile: ./docker/backend/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build: ./docker/nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend


volumes:
  static_volume: null
  postgres_data: null