# Generated by Django 4.1.2 on 2022-12-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_coursefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.CharField(default='img/no_image.svg', max_length=25, verbose_name='Cover'),
        ),
    ]
