# Generated by Django 4.1.2 on 2022-12-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_course_description_as_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description_as_markdown',
            field=models.BooleanField(default=False, verbose_name='Разметка Markdown'),
        ),
    ]
