# Generated by Django 4.1.2 on 2022-12-11 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0007_alter_course_options_alter_coursefeedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='feedback',
            field=models.TextField(default='No feedback', verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='rating',
            field=models.SmallIntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐'), (1, '⭐')], default=5, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
